### ISSUE TITLE
вопросы о доведении TeX-диплома в МАИ до защиты

### ISSUE THREAD

**Issue by oserikov** [Dju999/diplom#1]
На [форуме восьмого факультета МАИ](http://faq8.ru/read.php?19,12408,12426#msg-12426) я прочитал о том, что верстка диплома в TeX может усложнить жизнь, в сообщении была ссылка на этот репозиторий. Расскажите, если это возможно, о всём этом подробнее. На каком этапе и при каких обстоятельствах приходится отстаивать TeX-путь?

**Comment by oserikov** [comment]
Просто добавляю упоминание по нику чтобы прилетело уведомление: @Dju999

**Comment by Dju999** [comment]
Кажется, никаких сложностей с LaTeX не было, наоборот - один раз создаешь стилевой файл, которым потом можно пользоваться многократно. Плюс теховские файлы можно хранить в той же, что и программный код  - удобно вставлять в текст картинки (если он генерируются программно)

**Comment by oserikov** [comment]
@Dju999 Спасибо за ответ!
